$file = "E:\syson-rg\syson\backend\metamodel\syson-sysml-metamodel-edit\src\main\resources\plugin_zh.properties"
$c = [IO.File]::ReadAllText($file)

$map = @{
    # ElementFilterMembership
    '_UI_ElementFilterMembership_condition_feature = Condition' = '_UI_ElementFilterMembership_condition_feature = 条件'
    # Enumeration
    '_UI_EnumerationDefinition_enumeratedValue_feature = Enumerated Value' = '_UI_EnumerationDefinition_enumeratedValue_feature = 枚举值'
    '_UI_EnumerationUsage_enumerationDefinition_feature = Enumeration Definition' = '_UI_EnumerationUsage_enumerationDefinition_feature = 枚举定义'
    # EventOccurrence
    '_UI_EventOccurrenceUsage_eventOccurrence_feature = Event Occurrence' = '_UI_EventOccurrenceUsage_eventOccurrence_feature = 事件发生'
    '_UI_ExhibitStateUsage_exhibitedState_feature = Exhibited State' = '_UI_ExhibitStateUsage_exhibitedState_feature = 展示状态'
    # Expression
    '_UI_Expression_isModelLevelEvaluable_feature = Is Model Level Evaluable' = '_UI_Expression_isModelLevelEvaluable_feature = 模型级可评估'
    '_UI_Expression_function_feature = Function' = '_UI_Expression_function_feature = 函数'
    '_UI_Expression_result_feature = Result' = '_UI_Expression_result_feature = 结果'
    # Feature chain/ref
    '_UI_FeatureChainExpression_targetFeature_feature = Target Feature' = '_UI_FeatureChainExpression_targetFeature_feature = 目标特性'
    '_UI_FeatureChaining_chainingFeature_feature = Chaining Feature' = '_UI_FeatureChaining_chainingFeature_feature = 链式特性'
    '_UI_FeatureChaining_featureChained_feature = Feature Chained' = '_UI_FeatureChaining_featureChained_feature = 被链特性'
    '_UI_FeatureInverting_featureInverted_feature = Feature Inverted' = '_UI_FeatureInverting_featureInverted_feature = 被反转特性'
    '_UI_FeatureInverting_invertingFeature_feature = Inverting Feature' = '_UI_FeatureInverting_invertingFeature_feature = 反转特性'
    '_UI_FeatureInverting_owningFeature_feature = Owning Feature' = '_UI_FeatureInverting_owningFeature_feature = 所属特性'
    '_UI_FeatureMembership_ownedMemberFeature_feature = Owned Member Feature' = '_UI_FeatureMembership_ownedMemberFeature_feature = 拥有的成员特性'
    '_UI_FeatureMembership_owningType_feature = Owning Type' = '_UI_FeatureMembership_owningType_feature = 所属类型'
    '_UI_FeatureReferenceExpression_referent_feature = Referent' = '_UI_FeatureReferenceExpression_referent_feature = 指称对象'
    '_UI_FeatureTyping_owningFeature_feature = Owning Feature' = '_UI_FeatureTyping_owningFeature_feature = 所属特性'
    '_UI_FeatureTyping_type_feature = Type' = '_UI_FeatureTyping_type_feature = 类型'
    '_UI_FeatureTyping_typedFeature_feature = Typed Feature' = '_UI_FeatureTyping_typedFeature_feature = 被类型化特性'
    # FeatureValue
    '_UI_FeatureValue_isDefault_feature = Is Default' = '_UI_FeatureValue_isDefault_feature = 默认值'
    '_UI_FeatureValue_isInitial_feature = Is Initial' = '_UI_FeatureValue_isInitial_feature = 初始值'
    '_UI_FeatureValue_featureWithValue_feature = Feature With Value' = '_UI_FeatureValue_featureWithValue_feature = 带值特性'
    '_UI_FeatureValue_value_feature = Value' = '_UI_FeatureValue_value_feature = 值'
    # Flow
    '_UI_Flow_flowEnd_feature = Flow End' = '_UI_Flow_flowEnd_feature = 流端点'
    '_UI_Flow_interaction_feature = Interaction' = '_UI_Flow_interaction_feature = 交互'
    '_UI_Flow_payloadFeature_feature = Payload Feature' = '_UI_Flow_payloadFeature_feature = 载荷特性'
    '_UI_Flow_payloadType_feature = Payload Type' = '_UI_Flow_payloadType_feature = 载荷类型'
    '_UI_Flow_sourceOutputFeature_feature = Source Output Feature' = '_UI_Flow_sourceOutputFeature_feature = 源输出特性'
    '_UI_Flow_targetInputFeature_feature = Target Input Feature' = '_UI_Flow_targetInputFeature_feature = 目标输入特性'
    '_UI_FlowDefinition_flowEnd_feature = Flow End' = '_UI_FlowDefinition_flowEnd_feature = 流端点'
    '_UI_FlowUsage_flowDefinition_feature = Flow Definition' = '_UI_FlowUsage_flowDefinition_feature = 流定义'
    # For/If/Loop
    '_UI_ForLoopActionUsage_loopVariable_feature = Loop Variable' = '_UI_ForLoopActionUsage_loopVariable_feature = 循环变量'
    '_UI_ForLoopActionUsage_seqArgument_feature = Seq Argument' = '_UI_ForLoopActionUsage_seqArgument_feature = 序列参数'
    '_UI_FramedConcernMembership_ownedConcern_feature = Owned Concern' = '_UI_FramedConcernMembership_ownedConcern_feature = 拥有的关注点'
    '_UI_FramedConcernMembership_referencedConcern_feature = Referenced Concern' = '_UI_FramedConcernMembership_referencedConcern_feature = 被引用关注点'
    '_UI_Function_isModelLevelEvaluable_feature = Is Model Level Evaluable' = '_UI_Function_isModelLevelEvaluable_feature = 模型级可评估'
    '_UI_Function_expression_feature = Expression' = '_UI_Function_expression_feature = 表达式'
    '_UI_Function_result_feature = Result' = '_UI_Function_result_feature = 结果'
    '_UI_IfActionUsage_elseAction_feature = Else Action' = '_UI_IfActionUsage_elseAction_feature = 否则动作'
    '_UI_IfActionUsage_ifArgument_feature = If Argument' = '_UI_IfActionUsage_ifArgument_feature = 条件参数'
    '_UI_IfActionUsage_thenAction_feature = Then Action' = '_UI_IfActionUsage_thenAction_feature = 则动作'
    # Import
    '_UI_Import_isImportAll_feature = Is Import All' = '_UI_Import_isImportAll_feature = 导入全部'
    '_UI_Import_isRecursive_feature = Is Recursive' = '_UI_Import_isRecursive_feature = 递归'
    '_UI_Import_visibility_feature = Visibility' = '_UI_Import_visibility_feature = 可见性'
    '_UI_Import_importedElement_feature = Imported Element' = '_UI_Import_importedElement_feature = 被导入元素'
    '_UI_Import_importOwningNamespace_feature = Import Owning Namespace' = '_UI_Import_importOwningNamespace_feature = 导入所属命名空间'
    '_UI_IncludeUseCaseUsage_useCaseIncluded_feature = Use Case Included' = '_UI_IncludeUseCaseUsage_useCaseIncluded_feature = 被包含用例'
    '_UI_InstantiationExpression_argument_feature = Argument' = '_UI_InstantiationExpression_argument_feature = 参数'
    '_UI_InstantiationExpression_instantiatedType_feature = Instantiated Type' = '_UI_InstantiationExpression_instantiatedType_feature = 实例化类型'
    # Interface/Connection
    '_UI_InterfaceDefinition_interfaceEnd_feature = Interface End' = '_UI_InterfaceDefinition_interfaceEnd_feature = 接口端点'
    '_UI_InterfaceUsage_interfaceDefinition_feature = Interface Definition' = '_UI_InterfaceUsage_interfaceDefinition_feature = 接口定义'
    '_UI_ConnectionDefinition_connectionEnd_feature = Connection End' = '_UI_ConnectionDefinition_connectionEnd_feature = 连接端点'
    '_UI_ConnectionUsage_connectionDefinition_feature = Connection Definition' = '_UI_ConnectionUsage_connectionDefinition_feature = 连接定义'
    # Intersecting
    '_UI_Intersecting_intersectingType_feature = Intersecting Type' = '_UI_Intersecting_intersectingType_feature = 交叉类型'
    '_UI_Intersecting_typeIntersected_feature = Type Intersected' = '_UI_Intersecting_typeIntersected_feature = 被交叉类型'
    '_UI_Invariant_isNegated_feature = Is Negated' = '_UI_Invariant_isNegated_feature = 否定'
    '_UI_ItemUsage_itemDefinition_feature = Item Definition' = '_UI_ItemUsage_itemDefinition_feature = 项定义'
    '_UI_LibraryPackage_isStandard_feature = Is Standard' = '_UI_LibraryPackage_isStandard_feature = 标准'
    # Literals
    '_UI_LiteralBoolean_value_feature = Value' = '_UI_LiteralBoolean_value_feature = 值'
    '_UI_LiteralInteger_value_feature = Value' = '_UI_LiteralInteger_value_feature = 值'
    '_UI_LiteralRational_value_feature = Value' = '_UI_LiteralRational_value_feature = 值'
    '_UI_LiteralString_value_feature = Value' = '_UI_LiteralString_value_feature = 值'
    '_UI_LoopActionUsage_bodyAction_feature = Body Action' = '_UI_LoopActionUsage_bodyAction_feature = 循环体动作'
    # Membership misc
    '_UI_MembershipImport_importedMembership_feature = Imported Membership' = '_UI_MembershipImport_importedMembership_feature = 被导入成员'
    '_UI_MetadataAccessExpression_referencedElement_feature = Referenced Element' = '_UI_MetadataAccessExpression_referencedElement_feature = 被引用元素'
    '_UI_MetadataFeature_metaclass_feature = Metaclass' = '_UI_MetadataFeature_metaclass_feature = 元类'
    '_UI_MetadataUsage_metadataDefinition_feature = Metadata Definition' = '_UI_MetadataUsage_metadataDefinition_feature = 元数据定义'
    # Multiplicity
    '_UI_MultiplicityRange_bound_feature = Bound' = '_UI_MultiplicityRange_bound_feature = 界限'
    '_UI_MultiplicityRange_lowerBound_feature = Lower Bound' = '_UI_MultiplicityRange_lowerBound_feature = 下限'
    '_UI_MultiplicityRange_upperBound_feature = Upper Bound' = '_UI_MultiplicityRange_upperBound_feature = 上限'
    '_UI_NamespaceImport_importedNamespace_feature = Imported Namespace' = '_UI_NamespaceImport_importedNamespace_feature = 被导入命名空间'
    # Objective/Stakeholder
    '_UI_ObjectiveMembership_ownedObjectiveRequirement_feature = Owned Objective Requirement' = '_UI_ObjectiveMembership_ownedObjectiveRequirement_feature = 拥有的目标需求'
    '_UI_OccurrenceDefinition_isIndividual_feature = Is Individual' = '_UI_OccurrenceDefinition_isIndividual_feature = 个体'
    '_UI_OccurrenceUsage_isIndividual_feature = Is Individual' = '_UI_OccurrenceUsage_isIndividual_feature = 个体'
    '_UI_OccurrenceUsage_portionKind_feature = Portion Kind' = '_UI_OccurrenceUsage_portionKind_feature = 部分类型'
    '_UI_OccurrenceUsage_individualDefinition_feature = Individual Definition' = '_UI_OccurrenceUsage_individualDefinition_feature = 个体定义'
    '_UI_OccurrenceUsage_occurrenceDefinition_feature = Occurrence Definition' = '_UI_OccurrenceUsage_occurrenceDefinition_feature = 事件定义'
    '_UI_OperatorExpression_operator_feature = Operator' = '_UI_OperatorExpression_operator_feature = 运算符'
    '_UI_Package_filterCondition_feature = Filter Condition' = '_UI_Package_filterCondition_feature = 过滤条件'
    # Parameter
    '_UI_ParameterMembership_ownedMemberParameter_feature = Owned Member Parameter' = '_UI_ParameterMembership_ownedMemberParameter_feature = 拥有的成员参数'
    # Part/Port
    '_UI_PartUsage_partDefinition_feature = Part Definition' = '_UI_PartUsage_partDefinition_feature = 部件定义'
    '_UI_PerformActionUsage_performedAction_feature = Performed Action' = '_UI_PerformActionUsage_performedAction_feature = 执行的动作'
    '_UI_PortConjugation_conjugatedPortDefinition_feature = Conjugated Port Definition' = '_UI_PortConjugation_conjugatedPortDefinition_feature = 共轭端口定义'
    '_UI_PortConjugation_originalPortDefinition_feature = Original Port Definition' = '_UI_PortConjugation_originalPortDefinition_feature = 原始端口定义'
    '_UI_PortDefinition_conjugatedPortDefinition_feature = Conjugated Port Definition' = '_UI_PortDefinition_conjugatedPortDefinition_feature = 共轭端口定义'
    '_UI_PortUsage_portDefinition_feature = Port Definition' = '_UI_PortUsage_portDefinition_feature = 端口定义'
    # Redefinition/Subsetting
    '_UI_Redefinition_redefinedFeature_feature = Redefined Feature' = '_UI_Redefinition_redefinedFeature_feature = 被重定义特性'
    '_UI_Redefinition_redefiningFeature_feature = Redefining Feature' = '_UI_Redefinition_redefiningFeature_feature = 重定义特性'
    '_UI_ReferenceSubsetting_referencedFeature_feature = Referenced Feature' = '_UI_ReferenceSubsetting_referencedFeature_feature = 被引用特性'
    '_UI_ReferenceSubsetting_referencingFeature_feature = Referencing Feature' = '_UI_ReferenceSubsetting_referencingFeature_feature = 引用特性'
    # Rendering
    '_UI_RenderingDefinition_rendering_feature = Rendering' = '_UI_RenderingDefinition_rendering_feature = 渲染'
    '_UI_RenderingUsage_renderingDefinition_feature = Rendering Definition' = '_UI_RenderingUsage_renderingDefinition_feature = 渲染定义'
    # Requirement
    '_UI_RequirementConstraintMembership_kind_feature = Kind' = '_UI_RequirementConstraintMembership_kind_feature = 类型'
    '_UI_RequirementConstraintMembership_ownedConstraint_feature = Owned Constraint' = '_UI_RequirementConstraintMembership_ownedConstraint_feature = 拥有的约束'
    '_UI_RequirementConstraintMembership_referencedConstraint_feature = Referenced Constraint' = '_UI_RequirementConstraintMembership_referencedConstraint_feature = 被引用约束'
    '_UI_RequirementDefinition_reqId_feature = Req Id' = '_UI_RequirementDefinition_reqId_feature = 需求ID'
    '_UI_RequirementDefinition_text_feature = Text' = '_UI_RequirementDefinition_text_feature = 文本'
    '_UI_RequirementDefinition_actorParameter_feature = Actor Parameter' = '_UI_RequirementDefinition_actorParameter_feature = 角色参数'
    '_UI_RequirementDefinition_assumedConstraint_feature = Assumed Constraint' = '_UI_RequirementDefinition_assumedConstraint_feature = 假设约束'
    '_UI_RequirementDefinition_framedConcern_feature = Framed Concern' = '_UI_RequirementDefinition_framedConcern_feature = 框架关注点'
    '_UI_RequirementDefinition_requiredConstraint_feature = Required Constraint' = '_UI_RequirementDefinition_requiredConstraint_feature = 必需约束'
    '_UI_RequirementDefinition_stakeholderParameter_feature = Stakeholder Parameter' = '_UI_RequirementDefinition_stakeholderParameter_feature = 利益相关方参数'
    '_UI_RequirementDefinition_subjectParameter_feature = Subject Parameter' = '_UI_RequirementDefinition_subjectParameter_feature = 主体参数'
    '_UI_RequirementUsage_reqId_feature = Req Id' = '_UI_RequirementUsage_reqId_feature = 需求ID'
    '_UI_RequirementUsage_text_feature = Text' = '_UI_RequirementUsage_text_feature = 文本'
    '_UI_RequirementUsage_actorParameter_feature = Actor Parameter' = '_UI_RequirementUsage_actorParameter_feature = 角色参数'
    '_UI_RequirementUsage_assumedConstraint_feature = Assumed Constraint' = '_UI_RequirementUsage_assumedConstraint_feature = 假设约束'
    '_UI_RequirementUsage_framedConcern_feature = Framed Concern' = '_UI_RequirementUsage_framedConcern_feature = 框架关注点'
    '_UI_RequirementUsage_requiredConstraint_feature = Required Constraint' = '_UI_RequirementUsage_requiredConstraint_feature = 必需约束'
    '_UI_RequirementUsage_requirementDefinition_feature = Requirement Definition' = '_UI_RequirementUsage_requirementDefinition_feature = 需求定义'
    '_UI_RequirementUsage_stakeholderParameter_feature = Stakeholder Parameter' = '_UI_RequirementUsage_stakeholderParameter_feature = 利益相关方参数'
    '_UI_RequirementUsage_subjectParameter_feature = Subject Parameter' = '_UI_RequirementUsage_subjectParameter_feature = 主体参数'
    '_UI_RequirementVerificationMembership_ownedRequirement_feature = Owned Requirement' = '_UI_RequirementVerificationMembership_ownedRequirement_feature = 拥有的需求'
    '_UI_RequirementVerificationMembership_verifiedRequirement_feature = Verified Requirement' = '_UI_RequirementVerificationMembership_verifiedRequirement_feature = 已验证需求'
    '_UI_ResultExpressionMembership_ownedResultExpression_feature = Owned Result Expression' = '_UI_ResultExpressionMembership_ownedResultExpression_feature = 拥有的结果表达式'
    # Satisfy/Send
    '_UI_SatisfyRequirementUsage_satisfiedRequirement_feature = Satisfied Requirement' = '_UI_SatisfyRequirementUsage_satisfiedRequirement_feature = 被满足需求'
    '_UI_SatisfyRequirementUsage_satisfyingFeature_feature = Satisfying Feature' = '_UI_SatisfyRequirementUsage_satisfyingFeature_feature = 满足特性'
    '_UI_SendActionUsage_payloadArgument_feature = Payload Argument' = '_UI_SendActionUsage_payloadArgument_feature = 载荷参数'
    '_UI_SendActionUsage_receiverArgument_feature = Receiver Argument' = '_UI_SendActionUsage_receiverArgument_feature = 接收方参数'
    '_UI_SendActionUsage_senderArgument_feature = Sender Argument' = '_UI_SendActionUsage_senderArgument_feature = 发送方参数'
    # Specialization
    '_UI_Specialization_general_feature = General' = '_UI_Specialization_general_feature = 通用'
    '_UI_Specialization_owningType_feature = Owning Type' = '_UI_Specialization_owningType_feature = 所属类型'
    '_UI_Specialization_specific_feature = Specific' = '_UI_Specialization_specific_feature = 特定'
    '_UI_StakeholderMembership_ownedStakeholderParameter_feature = Owned Stakeholder Parameter' = '_UI_StakeholderMembership_ownedStakeholderParameter_feature = 拥有的利益相关方参数'
    # State
    '_UI_StateDefinition_isParallel_feature = Is Parallel' = '_UI_StateDefinition_isParallel_feature = 并行'
    '_UI_StateDefinition_doAction_feature = Do Action' = '_UI_StateDefinition_doAction_feature = 执行动作'
    '_UI_StateDefinition_entryAction_feature = Entry Action' = '_UI_StateDefinition_entryAction_feature = 入口动作'
    '_UI_StateDefinition_exitAction_feature = Exit Action' = '_UI_StateDefinition_exitAction_feature = 退出动作'
    '_UI_StateDefinition_state_feature = State' = '_UI_StateDefinition_state_feature = 状态'
    '_UI_StateSubactionMembership_kind_feature = Kind' = '_UI_StateSubactionMembership_kind_feature = 类型'
    '_UI_StateSubactionMembership_action_feature = Action' = '_UI_StateSubactionMembership_action_feature = 动作'
    '_UI_StateUsage_isParallel_feature = Is Parallel' = '_UI_StateUsage_isParallel_feature = 并行'
    '_UI_StateUsage_doAction_feature = Do Action' = '_UI_StateUsage_doAction_feature = 执行动作'
    '_UI_StateUsage_entryAction_feature = Entry Action' = '_UI_StateUsage_entryAction_feature = 入口动作'
    '_UI_StateUsage_exitAction_feature = Exit Action' = '_UI_StateUsage_exitAction_feature = 退出动作'
    '_UI_StateUsage_stateDefinition_feature = State Definition' = '_UI_StateUsage_stateDefinition_feature = 状态定义'
    # Step/Behavior
    '_UI_Step_behavior_feature = Behavior' = '_UI_Step_behavior_feature = 行为'
    '_UI_Step_parameter_feature = Parameter' = '_UI_Step_parameter_feature = 参数'
    '_UI_Behavior_parameter_feature = Parameter' = '_UI_Behavior_parameter_feature = 参数'
    '_UI_Behavior_step_feature = Step' = '_UI_Behavior_step_feature = 步骤'
    # Subclassification
    '_UI_Subclassification_owningClassifier_feature = Owning Classifier' = '_UI_Subclassification_owningClassifier_feature = 所属分类器'
    '_UI_Subclassification_subclassifier_feature = Subclassifier' = '_UI_Subclassification_subclassifier_feature = 子分类器'
    '_UI_Subclassification_superclassifier_feature = Superclassifier' = '_UI_Subclassification_superclassifier_feature = 超分类器'
    '_UI_SubjectMembership_ownedSubjectParameter_feature = Owned Subject Parameter' = '_UI_SubjectMembership_ownedSubjectParameter_feature = 拥有的主体参数'
    '_UI_Subsetting_owningFeature_feature = Owning Feature' = '_UI_Subsetting_owningFeature_feature = 所属特性'
    '_UI_Subsetting_subsettedFeature_feature = Subsetted Feature' = '_UI_Subsetting_subsettedFeature_feature = 被子集特性'
    '_UI_Subsetting_subsettingFeature_feature = Subsetting Feature' = '_UI_Subsetting_subsettingFeature_feature = 子集特性'
    # Terminate
    '_UI_TerminateActionUsage_terminatedOccurrenceArgument_feature = Terminated Occurrence Argument' = '_UI_TerminateActionUsage_terminatedOccurrenceArgument_feature = 终止事件参数'
    # TextualRepresentation
    '_UI_TextualRepresentation_body_feature = Body' = '_UI_TextualRepresentation_body_feature = 正文'
    '_UI_TextualRepresentation_language_feature = Language' = '_UI_TextualRepresentation_language_feature = 语言'
    '_UI_TextualRepresentation_representedElement_feature = Represented Element' = '_UI_TextualRepresentation_representedElement_feature = 被表示元素'
    # Transition
    '_UI_TransitionFeatureMembership_kind_feature = Kind' = '_UI_TransitionFeatureMembership_kind_feature = 类型'
    '_UI_TransitionFeatureMembership_transitionFeature_feature = Transition Feature' = '_UI_TransitionFeatureMembership_transitionFeature_feature = 转换特性'
    '_UI_TransitionUsage_effectAction_feature = Effect Action' = '_UI_TransitionUsage_effectAction_feature = 效果动作'
    '_UI_TransitionUsage_guardExpression_feature = Guard Expression' = '_UI_TransitionUsage_guardExpression_feature = 守卫表达式'
    '_UI_TransitionUsage_source_feature = Source' = '_UI_TransitionUsage_source_feature = 源'
    '_UI_TransitionUsage_succession_feature = Succession' = '_UI_TransitionUsage_succession_feature = 继承'
    '_UI_TransitionUsage_target_feature = Target' = '_UI_TransitionUsage_target_feature = 目标'
    '_UI_TransitionUsage_triggerAction_feature = Trigger Action' = '_UI_TransitionUsage_triggerAction_feature = 触发动作'
    '_UI_TriggerInvocationExpression_kind_feature = Kind' = '_UI_TriggerInvocationExpression_kind_feature = 类型'
    # TypeFeaturing
    '_UI_TypeFeaturing_featureOfType_feature = Feature Of Type' = '_UI_TypeFeaturing_featureOfType_feature = 类型特性'
    '_UI_TypeFeaturing_featuringType_feature = Featuring Type' = '_UI_TypeFeaturing_featuringType_feature = 特性化类型'
    '_UI_TypeFeaturing_owningFeatureOfType_feature = Owning Feature Of Type' = '_UI_TypeFeaturing_owningFeatureOfType_feature = 所属类型特性'
    # Unioning
    '_UI_Unioning_typeUnioned_feature = Type Unioned' = '_UI_Unioning_typeUnioned_feature = 被联合类型'
    '_UI_Unioning_unioningType_feature = Unioning Type' = '_UI_Unioning_unioningType_feature = 联合类型'
    # UseCase
    '_UI_UseCaseDefinition_includedUseCase_feature = Included Use Case' = '_UI_UseCaseDefinition_includedUseCase_feature = 被包含用例'
    '_UI_UseCaseUsage_includedUseCase_feature = Included Use Case' = '_UI_UseCaseUsage_includedUseCase_feature = 被包含用例'
    '_UI_UseCaseUsage_useCaseDefinition_feature = Use Case Definition' = '_UI_UseCaseUsage_useCaseDefinition_feature = 用例定义'
    # Variant
    '_UI_VariantMembership_ownedVariantUsage_feature = Owned Variant Usage' = '_UI_VariantMembership_ownedVariantUsage_feature = 拥有的变体使用'
    # Verification
    '_UI_VerificationCaseDefinition_verifiedRequirement_feature = Verified Requirement' = '_UI_VerificationCaseDefinition_verifiedRequirement_feature = 已验证需求'
    '_UI_VerificationCaseUsage_verificationCaseDefinition_feature = Verification Case Definition' = '_UI_VerificationCaseUsage_verificationCaseDefinition_feature = 验证案例定义'
    '_UI_VerificationCaseUsage_verifiedRequirement_feature = Verified Requirement' = '_UI_VerificationCaseUsage_verifiedRequirement_feature = 已验证需求'
    # View
    '_UI_ViewDefinition_satisfiedViewpoint_feature = Satisfied Viewpoint' = '_UI_ViewDefinition_satisfiedViewpoint_feature = 满足的视点'
    '_UI_ViewDefinition_view_feature = View' = '_UI_ViewDefinition_view_feature = 视图'
    '_UI_ViewDefinition_viewCondition_feature = View Condition' = '_UI_ViewDefinition_viewCondition_feature = 视图条件'
    '_UI_ViewDefinition_viewRendering_feature = View Rendering' = '_UI_ViewDefinition_viewRendering_feature = 视图渲染'
    '_UI_ViewpointDefinition_viewpointStakeholder_feature = Viewpoint Stakeholder' = '_UI_ViewpointDefinition_viewpointStakeholder_feature = 视点利益相关方'
    '_UI_ViewpointUsage_viewpointDefinition_feature = Viewpoint Definition' = '_UI_ViewpointUsage_viewpointDefinition_feature = 视点定义'
    '_UI_ViewpointUsage_viewpointStakeholder_feature = Viewpoint Stakeholder' = '_UI_ViewpointUsage_viewpointStakeholder_feature = 视点利益相关方'
    '_UI_ViewRenderingMembership_ownedRendering_feature = Owned Rendering' = '_UI_ViewRenderingMembership_ownedRendering_feature = 拥有的渲染'
    '_UI_ViewRenderingMembership_referencedRendering_feature = Referenced Rendering' = '_UI_ViewRenderingMembership_referencedRendering_feature = 被引用渲染'
    '_UI_ViewUsage_exposedElement_feature = Exposed Element' = '_UI_ViewUsage_exposedElement_feature = 暴露的元素'
    '_UI_ViewUsage_satisfiedViewpoint_feature = Satisfied Viewpoint' = '_UI_ViewUsage_satisfiedViewpoint_feature = 满足的视点'
    '_UI_ViewUsage_viewCondition_feature = View Condition' = '_UI_ViewUsage_viewCondition_feature = 视图条件'
    '_UI_ViewUsage_viewDefinition_feature = View Definition' = '_UI_ViewUsage_viewDefinition_feature = 视图定义'
    '_UI_ViewUsage_viewRendering_feature = View Rendering' = '_UI_ViewUsage_viewRendering_feature = 视图渲染'
    # While
    '_UI_WhileLoopActionUsage_untilArgument_feature = Until Argument' = '_UI_WhileLoopActionUsage_untilArgument_feature = 直到参数'
    '_UI_WhileLoopActionUsage_whileArgument_feature = While Argument' = '_UI_WhileLoopActionUsage_whileArgument_feature = 当参数'
    # Remaining Accept/Action/Allocation/etc
    '_UI_AcceptActionUsage_payloadArgument_feature = Payload Argument' = '_UI_AcceptActionUsage_payloadArgument_feature = 载荷参数'
    '_UI_AcceptActionUsage_payloadParameter_feature = Payload Parameter' = '_UI_AcceptActionUsage_payloadParameter_feature = 载荷形参'
    '_UI_AcceptActionUsage_receiverArgument_feature = Receiver Argument' = '_UI_AcceptActionUsage_receiverArgument_feature = 接收方参数'
    '_UI_ActionDefinition_action_feature = Action' = '_UI_ActionDefinition_action_feature = 动作'
    '_UI_ActionUsage_actionDefinition_feature = Action Definition' = '_UI_ActionUsage_actionDefinition_feature = 动作定义'
    '_UI_ActorMembership_ownedActorParameter_feature = Owned Actor Parameter' = '_UI_ActorMembership_ownedActorParameter_feature = 拥有的角色参数'
    '_UI_AllocationDefinition_allocation_feature = Allocation' = '_UI_AllocationDefinition_allocation_feature = 分配'
    '_UI_AllocationUsage_allocationDefinition_feature = Allocation Definition' = '_UI_AllocationUsage_allocationDefinition_feature = 分配定义'
    '_UI_AnalysisCaseDefinition_resultExpression_feature = Result Expression' = '_UI_AnalysisCaseDefinition_resultExpression_feature = 结果表达式'
    '_UI_AnalysisCaseUsage_analysisCaseDefinition_feature = Analysis Case Definition' = '_UI_AnalysisCaseUsage_analysisCaseDefinition_feature = 分析案例定义'
    '_UI_AnalysisCaseUsage_resultExpression_feature = Result Expression' = '_UI_AnalysisCaseUsage_resultExpression_feature = 结果表达式'
    '_UI_AssertConstraintUsage_assertedConstraint_feature = Asserted Constraint' = '_UI_AssertConstraintUsage_assertedConstraint_feature = 断言约束'
    '_UI_AssignmentActionUsage_referent_feature = Referent' = '_UI_AssignmentActionUsage_referent_feature = 指称对象'
    '_UI_AssignmentActionUsage_targetArgument_feature = Target Argument' = '_UI_AssignmentActionUsage_targetArgument_feature = 目标参数'
    '_UI_AssignmentActionUsage_valueExpression_feature = Value Expression' = '_UI_AssignmentActionUsage_valueExpression_feature = 值表达式'
    '_UI_Association_associationEnd_feature = Association End' = '_UI_Association_associationEnd_feature = 关联端点'
    '_UI_Association_relatedType_feature = Related Type' = '_UI_Association_relatedType_feature = 关联类型'
    '_UI_Association_sourceType_feature = Source Type' = '_UI_Association_sourceType_feature = 源类型'
    '_UI_Association_targetType_feature = Target Type' = '_UI_Association_targetType_feature = 目标类型'
    '_UI_AttributeUsage_attributeDefinition_feature = Attribute Definition' = '_UI_AttributeUsage_attributeDefinition_feature = 属性定义'
    '_UI_BooleanExpression_predicate_feature = Predicate' = '_UI_BooleanExpression_predicate_feature = 谓词'
    '_UI_CalculationDefinition_calculation_feature = Calculation' = '_UI_CalculationDefinition_calculation_feature = 计算'
    '_UI_CalculationUsage_calculationDefinition_feature = Calculation Definition' = '_UI_CalculationUsage_calculationDefinition_feature = 计算定义'
    '_UI_CaseDefinition_actorParameter_feature = Actor Parameter' = '_UI_CaseDefinition_actorParameter_feature = 角色参数'
    '_UI_CaseDefinition_objectiveRequirement_feature = Objective Requirement' = '_UI_CaseDefinition_objectiveRequirement_feature = 目标需求'
    '_UI_CaseDefinition_subjectParameter_feature = Subject Parameter' = '_UI_CaseDefinition_subjectParameter_feature = 主体参数'
    '_UI_CaseUsage_actorParameter_feature = Actor Parameter' = '_UI_CaseUsage_actorParameter_feature = 角色参数'
    '_UI_CaseUsage_caseDefinition_feature = Case Definition' = '_UI_CaseUsage_caseDefinition_feature = 案例定义'
    '_UI_CaseUsage_objectiveRequirement_feature = Objective Requirement' = '_UI_CaseUsage_objectiveRequirement_feature = 目标需求'
    '_UI_CaseUsage_subjectParameter_feature = Subject Parameter' = '_UI_CaseUsage_subjectParameter_feature = 主体参数'
    '_UI_Classifier_ownedSubclassification_feature = Owned Subclassification' = '_UI_Classifier_ownedSubclassification_feature = 拥有的子分类'
    '_UI_ConcernUsage_concernDefinition_feature = Concern Definition' = '_UI_ConcernUsage_concernDefinition_feature = 关注点定义'
    '_UI_ConjugatedPortDefinition_originalPortDefinition_feature = Original Port Definition' = '_UI_ConjugatedPortDefinition_originalPortDefinition_feature = 原始端口定义'
    '_UI_ConjugatedPortDefinition_ownedPortConjugator_feature = Owned Port Conjugator' = '_UI_ConjugatedPortDefinition_ownedPortConjugator_feature = 拥有的端口共轭器'
    '_UI_ConjugatedPortTyping_conjugatedPortDefinition_feature = Conjugated Port Definition' = '_UI_ConjugatedPortTyping_conjugatedPortDefinition_feature = 共轭端口定义'
    '_UI_ConjugatedPortTyping_portDefinition_feature = Port Definition' = '_UI_ConjugatedPortTyping_portDefinition_feature = 端口定义'
    '_UI_Conjugation_conjugatedType_feature = Conjugated Type' = '_UI_Conjugation_conjugatedType_feature = 共轭类型'
    '_UI_Conjugation_originalType_feature = Original Type' = '_UI_Conjugation_originalType_feature = 原始类型'
    '_UI_Conjugation_owningType_feature = Owning Type' = '_UI_Conjugation_owningType_feature = 所属类型'
    '_UI_Connector_association_feature = Association' = '_UI_Connector_association_feature = 关联'
    '_UI_Connector_connectorEnd_feature = Connector End' = '_UI_Connector_connectorEnd_feature = 连接器端点'
    '_UI_Connector_defaultFeaturingType_feature = Default Featuring Type' = '_UI_Connector_defaultFeaturingType_feature = 默认特性化类型'
    '_UI_Connector_relatedFeature_feature = Related Feature' = '_UI_Connector_relatedFeature_feature = 关联特性'
    '_UI_Connector_sourceFeature_feature = Source Feature' = '_UI_Connector_sourceFeature_feature = 源特性'
    '_UI_Connector_targetFeature_feature = Target Feature' = '_UI_Connector_targetFeature_feature = 目标特性'
    '_UI_ConstraintUsage_constraintDefinition_feature = Constraint Definition' = '_UI_ConstraintUsage_constraintDefinition_feature = 约束定义'
    '_UI_CrossSubsetting_crossedFeature_feature = Crossed Feature' = '_UI_CrossSubsetting_crossedFeature_feature = 被交叉特性'
    '_UI_CrossSubsetting_crossingFeature_feature = Crossing Feature' = '_UI_CrossSubsetting_crossingFeature_feature = 交叉特性'
    '_UI_Dependency_client_feature = Client' = '_UI_Dependency_client_feature = 客户端'
    '_UI_Dependency_supplier_feature = Supplier' = '_UI_Dependency_supplier_feature = 提供者'
    '_UI_Differencing_differencingType_feature = Differencing Type' = '_UI_Differencing_differencingType_feature = 差异类型'
    '_UI_Differencing_typeDifferenced_feature = Type Differenced' = '_UI_Differencing_typeDifferenced_feature = 被差异类型'
    '_UI_Disjoining_disjoiningType_feature = Disjoining Type' = '_UI_Disjoining_disjoiningType_feature = 分离类型'
    '_UI_Disjoining_owningType_feature = Owning Type' = '_UI_Disjoining_owningType_feature = 所属类型'
    '_UI_Disjoining_typeDisjoined_feature = Type Disjoined' = '_UI_Disjoining_typeDisjoined_feature = 被分离类型'
    '_UI_Documentation_documentedElement_feature = Documented Element' = '_UI_Documentation_documentedElement_feature = 被文档化元素'
    '_UI_Unknown_feature = Unspecified' = '_UI_Unknown_feature = 未指定'
}

foreach ($k in $map.Keys) {
    $c = $c.Replace($k, $map[$k])
}

[IO.File]::WriteAllText($file, $c)
Write-Host "All feature labels translated successfully"
